### PR TITLE
Update parser functionality and fix bugs

### LINKED ISSUE #130: Fix untag command implementation
- Verify single tag deletion
- Fix bug described below

### PR DESCRIPTION
**Pull request by iuhiah**
Fixes #130

### CODE REVIEW

File: src/main/java/seedu/innsync/logic/commands/UntagCommand.java [hunk 1]
```diff
@@ -83,7 +82,7 @@ public static Person removeTagsPerson(Person personToCopy,
         if (!toRemoveTag.isEmpty()) {
             Tag tagToRemove = new Tag(toRemoveTag);
             if (!tagList.contains(tagToRemove)) {
-                throw new CommandException(String.format(MESSAGE_FAILURE_TAG, toRemoveBookingTag));
+                throw new CommandException(String.format(MESSAGE_FAILURE_TAG, toRemoveTag));
```
Comment (varsha13152) [inline src/main/java/seedu/innsync/logic/commands/UntagCommand.java:85]: Great to see that you handled errors! Might wanna add logging as its part of this week's deliverables  :)

File: src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java [hunk 2]
```diff
@@ -18,30 +18,29 @@ public class UntagCommandParser implements Parser<UntagCommand> {
...
-        if (hasBookingTag == hasTag) {
+        if (!onlyOnePrefixPresent(argMultimap, PREFIX_BOOKINGTAG, PREFIX_TAG)) {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, UntagCommand.MESSAGE_USAGE));
         }
+
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_BOOKINGTAG, PREFIX_TAG);
         Index index = ParserUtil.parseIndex(argMultimap.getPreamble());
-        String bookingTag = argMultimap.getValue(PREFIX_BOOKINGTAG).orElse("");
         String tag = argMultimap.getValue(PREFIX_TAG).orElse("");
+        String bookingTag = argMultimap.getValue(PREFIX_BOOKINGTAG).orElse("");
```
Comment (Reshiro) [inline src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java:35]: Good catch on moving this line here.

File: src/main/java/seedu/innsync/logic/commands/UntagCommand.java (hunk 1 above)
Comment (Reshiro) [inline src/main/java/seedu/innsync/logic/commands/UntagCommand.java:85]: I really like how we can handle both types of tags now.

File: src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java [hunk 3]
```diff
@@ -18,30 +18,29 @@ public class UntagCommandParser implements Parser<UntagCommand> {
     /**
      * Parses the given {@code String} of arguments in the context of the TagCommand
      * and returns a TagCommand object for execution.
+     * Only allows one tag to be removed at a time.
```
Comment (Reshiro) [inline src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java:21]: The updated Javadoc on parse() is concise and clearly explains the method’s behavior, nice touch!

File: src/main/java/seedu/innsync/logic/commands/UntagCommand.java [hunk 4]
```diff
@@ -26,8 +26,7 @@ public class UntagCommand extends Command {
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Removes the tag from the contact identified by the index number used in the displayed person list.\n"
             + "Parameters: INDEX (must be a positive integer) "
-            + PREFIX_TAG + "TAG\n"
-            + "or "
+            + PREFIX_TAG + "TAG\n" + "OR "
```
Comment (Reshiro) [inline src/main/java/seedu/innsync/logic/commands/UntagCommand.java:29]: Good catch on the style for our help messages.

File: src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java [hunk 5]
```diff
@@ -18,30 +18,29 @@ public class UntagCommandParser implements Parser<UntagCommand> {
...
     }
+
     /**
-     * Returns true if at least one of the prefixes is present in the {@code ArgumentMultimap}.
+     * Returns true if only one of the prefixes is present in the {@code ArgumentMultimap}.
      */
-    private static boolean atLeastOnePrefixPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
-        return Stream.of(prefixes).anyMatch(prefix -> argumentMultimap.getValue(prefix).isPresent());
+    private static boolean onlyOnePrefixPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
+        return Stream.of(prefixes).filter(prefix -> argumentMultimap.getValue(prefix).isPresent()).count() == 1;
```
Comment (Reshiro) [inline src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java:44]: Thanks for making this change, it fits our program better.

**Review by Reshiro — COMMENTED** [review]
LGTM
