### PR TITLE
Fix tag removal logic and exception message

### LINKED ISSUE #349: Unable to remove auto-populated tags
Image

### PR DESCRIPTION
**Pull request by iuhiah**
image
 Fixes #349

### CODE REVIEW

File: src/main/java/seedu/innsync/logic/commands/UntagCommand.java [hunk 1]
```diff
@@ -88,33 +81,36 @@ public CommandResult execute(Model model) throws CommandException {
...
+        Person copiedPerson = new Person(
+            personToCopy.getName(),
+            personToCopy.getPhone(),
+            personToCopy.getEmail(),
+            personToCopy.getAddress(),
+            personToCopy.getMemo(),
+            personToCopy.getRequests(),
+            updatedBookingTags,
+            personToCopy.getTags(),
+            personToCopy.getStarred());
```
Comment (iuhiah) [inline src/main/java/seedu/innsync/logic/commands/UntagCommand.java:103]:
```suggestion
              personToCopy.getName(),
              personToCopy.getPhone(),
              personToCopy.getEmail(),
              personToCopy.getAddress(),
              personToCopy.getMemo(),
              personToCopy.getRequests(),
              updatedBookingTags,
              personToCopy.getTags(),
              personToCopy.getStarred());
```

**Review by TanXingZhong — APPROVED** [review]
lgtm
