### PR TITLE
Fix argument passing in untag command parser

### LINKED ISSUE #127: Bug in untag command for invalid booking tags
# Bug in functionality for untag command

## Describe the bug
Attempting to remove an invalid booking tag will not throw an error or success message

## To Reproduce
`untag 1 b/BeachHouse from/2025-06-01 to/2025-06-01`

## Expected behavior
Error message shown

# Screenshots
Image
Image

### PR DESCRIPTION
**Pull request by iuhiah**
Fix #127

### CODE REVIEW

File: src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ public UntagCommand parse(String args) throws ParseException {
         String bookingTag = argMultimap.getValue(PREFIX_BOOKINGTAG).orElse("");
         String tag = argMultimap.getValue(PREFIX_TAG).orElse("");
 
-        return new UntagCommand(index, bookingTag, tag);
+        return new UntagCommand(index, tag, bookingTag);
```
Comment (TanXingZhong) [inline src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java:39]: Oppsy, nice catch. My bad 👍

**Review by TanXingZhong — APPROVED** [review]
